export const LOCALE_CHANGE = "LOCALE_CHANGE";

export const SHOW_MODAL = "SHOW_MODAL";
export const HIDE_MODAL = "HIDE_MODAL";

export const CONFIRM_YES = "CONFIRM_YES";
export const CONFIRM_NO = "CONFIRM_NO";

export const LOGIN_REQUESTED = 'LOGIN_REQUESTED';
export const LOGIN_SUCCEEDED = 'LOGIN_SUCCEEDED';
export const LOGIN_FAILED = 'LOGIN_FAILED';

export const REGISTER_REQUESTED = 'REGISTER_REQUESTED';
export const REGISTER_SUCCEEDED = 'REGISTER_SUCCEEDED';
export const REGISTER_FAILED = 'REGISTER_FAILED';

export const GET_POSTS_REQUESTED = 'GET_POSTS_REQUESTED';
export const GET_POSTS_SUCCEEDED = 'GET_POSTS_SUCCEEDED';
export const GET_POSTS_FAILED = 'GET_POSTS_FAILED';